#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

# Import common cmd
source ../settings/scripts/experimental_helper.sh
source ../settings/scripts/_common.sh

# Retrieve arguments
domain=$(ynh_app_setting_get $app domain)

#=================================================
# STANDARD BACKUP STEPS
#=================================================

# Copy NGINX configuration
domain=$(ynh_app_setting_get "$app" domain)
ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "nginx.conf"
ynh_backup "/etc/nginx/conf.d/monitorix_status.conf" "monitorix_status.conf"

# Copy hook
ynh_backup "/usr/share/yunohost/hooks/post_iptable_rules/50-$app"

# Copy Monitorix configuration
ynh_backup "/etc/monitorix" "config"

# Copy Monitorix data
ynh_backup "/var/lib/monitorix" "data"

