#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Import common cmd
source ./experimental_helper.sh
source ./_common.sh

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)

#=================================================
# STANDARD REMOVE
#=================================================

# Stop service
systemctl stop monitorix.service

# Drop MySQL database and user
dbname=$app
dbuser=$app
ynh_mysql_drop_db "$dbname" || true
ynh_mysql_drop_user "$dbuser" || true

# Remove data
ynh_secure_remove /var/lib/monitorix
ynh_secure_remove /usr/share/yunohost/hooks/post_iptable_rules/50-$app

# Remove nginx config
ynh_secure_remove "/etc/nginx/conf.d/monitorix_status.conf"
ynh_remove_nginx_config

# Autoremove package
ynh_remove_app_dependencies
ynh_package_autoremove monitorix

yunohost service remove monitorix
